# Generated by Django 3.0.7 on 2020-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_to_image', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('publishedAt', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
