# Generated by Django 3.0.7 on 2020-10-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpress', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='news_details',
        ),
    ]
