# Generated by Django 3.0.7 on 2020-10-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpress', '0002_auto_20201008_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_details',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news_details',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news_details',
            name='publishedAt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news_details',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news_details',
            name='url_to_image',
            field=models.TextField(null=True),
        ),
    ]
