# Generated by Django 3.0.7 on 2020-10-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpress', '0004_news_details_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_details',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
