# Generated by Django 3.0.7 on 2020-10-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpress', '0005_auto_20201008_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news_details',
        ),
    ]
